[package]
name = "rust-sound-flipper"
version = "0.1.0"
edition = "2021"

[dependencies]
lame = "0.1.3"
minimp3 = "0.5.1"
tower = "0.5.1"

symphonia = { version = "0.5.4", features = ["mp3"] }
clap = { version = "4.2", features = ["derive"] }
hound = "3.5.1"
